[package]
name = "nv-config"
version.workspace = true
edition.workspace = true
license.workspace = true

[[bin]]
name = "NeedleVoiceConfig"
path = "src/main.rs"

[dependencies]
nv-core = { path = "../nv-core" }
eframe = { version = "0.36", default-features = false, features = ["default_fonts", "glow"] }
egui_extras = "0.36"
cpal = "0.18"
log = "0.4"

[build-dependencies]
nv-version = { path = "../nv-version" }
